version: '3'
services:
  app_db:
    image: postgres:11.1-alpine
    container_name: app
    environment:
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
#      POSTGRES_USER: communities_app
  app:
    image: python:3.7.1-alpine3.8
    container_name: app
    environment:
      #DB CONFIGURATION
      DB_NAME: app
      DB_USER: postgres
      DB_PASS: app
      DB_HOST: app_db
    restart: always
    build:
      context: .
    volumes:
      - .:/usr/app/
    ports:
      - 5000:5000
    depends_on:
      - app_db
